# Generated by Django 5.0.4 on 2025-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('photo', models.ImageField(upload_to='students/')),
                ('center_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
