# Generated by Django 5.0.4 on 2025-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('total_questions', models.PositiveIntegerField()),
                ('marks_per_question', models.FloatField()),
                ('negative_marking', models.FloatField(help_text='Marks deducted per wrong answer (use 0 if none)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
