# Generated by Django 5.0.4 on 2025-12-10 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testattempt_studentanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='not_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('student', 'scheduled_test')},
        ),
    ]
