# Generated by Django 5.0.6 on 2025-12-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_studentanswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='scheduled_test',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TestAttempt',
        ),
    ]
