# Generated by Django 5.0.6 on 2025-12-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_testattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('total_questions_attempted', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('submitted', 'Submitted'), ('timeout', 'Timeout')], default='ongoing', max_length=20)),
                ('scheduled_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scheduledtest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.FloatField(default=0)),
                ('is_marked_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.studenttestattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
