# Generated by Django 5.0.6 on 2025-12-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_studenttestattempt_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_marked_review',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='time_taken_seconds',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='total_correct',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='total_questions_attempted',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='chosen_option',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='time_allowed_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
