# Generated by Django 5.0.6 on 2025-12-11 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_studentanswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='negative_marking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduledtest',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduledtest',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam'),
        ),
        migrations.AlterField(
            model_name='scheduledtest',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studenttestattempt',
            name='time_allowed_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
