# Generated by Django 5.0.6 on 2025-12-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_studenttestattempt_total_questions_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='time_allowed_minutes',
        ),
        migrations.RemoveField(
            model_name='studenttestattempt',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_marked_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studenttestattempt'),
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='chosen_option',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='marked_for_review',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='saved_at',
        ),
    ]
