# Generated by Django 5.0.6 on 2025-12-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_freetestattempt_freetestanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
