# Generated by Django 5.0.6 on 2025-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_exam_examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_free_test',
            field=models.BooleanField(default=False),
        ),
    ]
