# Generated by Django 5.0.6 on 2025-12-17 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_exam_is_free_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_free_test',
        ),
        migrations.CreateModel(
            name='FreeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='FreeTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.freetestattempt')),
            ],
        ),
        migrations.CreateModel(
            name='FreeTestButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam')),
            ],
        ),
        migrations.AddField(
            model_name='freetestattempt',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.freetestbutton'),
        ),
    ]
