# Generated by Django 5.0.6 on 2025-12-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_exam_is_free_test_freetestattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('marks_per_question', models.FloatField()),
                ('negative_marking', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
