# Generated by Django 5.0.6 on 2025-12-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_exammaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamMaster',
        ),
    ]
