# Generated by Django 5.0.6 on 2025-12-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_exammaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateTimeField()),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='app.exam')),
            ],
        ),
    ]
