# Generated by Django 5.0.6 on 2025-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_examtask_delete_examactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtask',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
