# Generated by Django 5.0.6 on 2025-12-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_studentexamattempt_studentexamanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamanswer',
            name='is_marked_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamanswer',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
