# Generated by Django 5.0.6 on 2025-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_studentexamanswer_is_marked_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamanswer',
            name='remaining_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
