# Generated by Django 5.0.6 on 2025-12-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_studentexamanswer_remaining_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='started_at',
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
