# Generated by Django 5.0.6 on 2025-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_studentexamattempt_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='remaining_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
