# Generated by Django 5.0.6 on 2025-12-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_studentexamattempt_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamanswer',
            unique_together={('attempt', 'exam_question')},
        ),
        migrations.AlterField(
            model_name='studentexamanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.studentexamattempt'),
        ),
        migrations.RemoveField(
            model_name='studentexamanswer',
            name='remaining_seconds',
        ),
    ]
