# Generated by Django 5.0.6 on 2025-12-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_studentexamanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='remaining_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
