# Generated by Django 5.0.6 on 2025-12-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_studentexamattempt_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentexamanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='studentexamanswer',
            name='exam_question',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='ExamTask',
        ),
        migrations.DeleteModel(
            name='StudentExamAnswer',
        ),
        migrations.DeleteModel(
            name='StudentExamAttempt',
        ),
    ]
