# Generated by Django 5.0.6 on 2025-12-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_studentexamanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetestattempt',
            name='candidate_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freetestattempt',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='freetestattempt',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
