# Generated by Django 5.0.6 on 2026-02-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_student_created_at_alter_student_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_screenshot',
        ),
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
